### ISSUE TITLE
Extra space

### ISSUE THREAD

**Issue by ImBoing** [khrome/ascii-art-font#2]
I was curious if I was doing something wrong but it returns the text with so much extra space under it 
<img width="474" alt="Screen Shot 2020-04-22 at 10 46 08 AM" src="https://user-images.githubusercontent.com/62665535/79996482-83351680-8486-11ea-9c08-3164f2ad19e9.png">

**Comment by khrome** [comment]
the characters extend below the baseline for characters which extend beneath it like 'y' or 'g'.

Relevant: https://en.wikipedia.org/wiki/Font#Metrics
